services:
  # PostgreSQL Database Service
  db:
    container_name: PostgreSQL_Database
    image: postgres # Use the official Postgres image
    restart: always
    env_file: ./.env
    ports:
      # Map port 5432 on the host to 5432 in the container for external access (optional)
      - "5432:5432"
    volumes:
      # Persist database data even if the container is removed
      - ./db/postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Python App Service
  app:
    container_name: Python_App
    build: . # Build the image from the Dockerfile in the current directory
    env_file: ./.env
    restart: unless-stopped
    depends_on:
      db: # Wait for the db container to start before starting the app
        condition: service_healthy # wait for db to be ready to recieve connections
    environment:
      - IS_DOCKER_CONTAINER=True

# Define a named volume for data persistence
volumes:
  postgres_data: